server:
  port: ${PORT:8080}
  ssl:
    enabled: false

spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
    auto-commit: false
  flyway:
    out-of-order: true
    table: "webhooknp_schema_history"
    schemas: ${DB_SCHEMA:webhooknp}
  jpa:
    properties:
      hibernate.default_schema: ${DB_SCHEMA:webhooknp}
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
